### ISSUE TITLE
rbenv configuration in 3-tiny_web_rpmbuild.ipynb

### ISSUE THREAD

**Issue by triggers** [axsh/nii-project-2016#30]
When testing on master branch commit 10726ae078e7f3a795d69dbcbebb82427666ca86, in the
http://192.168.2.24:19999/notebooks/3-tiny_web_rpmbuild.ipynb
notebook, the check for "Task: Configure rbenv" reports "Version:
Passed Gems: Passed", but the "rbenv build wrapper" setting in
"job/tiny_web.rpmbuild/configure" is not active.

Therefore when the job is run, it fails with: "/bin/sh: bundle: command not found".

ref:
https://github.com/axsh/nii-project-2016/tree/10726ae078e7f3a795d69dbcbebb82427666ca86

**Comment by toros11** [comment]
Solved in #36
