### ISSUE TITLE
Notebook List (Final Plan)

### ISSUE THREAD

**Issue by k-oyakata** [axsh/nii-project-2016#55]
## 1日目
1. Githubの使い方を学ぼう

2. HipChatの使い方を覚えよう
  * 101_HipChat_セットアップ.pdf -> 101_HipChat_setup.ipynb
  * convert only

3. Jenkinsをインストールしてみよう
  * 1-introduction.ipynb -> 102_Jenkins_setup.ipynb
  * auto

4. JenkinsにJobを登録し、実行してみよう
  * 103_Jenkins_任意のスクリプト実行ジョブ.pdf -> 103_Jenkins_script_job.ipynb
  * auto

5. GithubのGitリポジトリからソースコードをPullできるようにしてみよう
  * 104_Jenkins_GitHubポーリング連動.pdf -> 104_Jenkins_Github_setup.ipynb
    + form 1-introduction. part of set up only.
  * auto

6. テスト結果をHipChatにレポートしてみよう
  * 105_Jenkins_HipChatへのレポート.pdf -> 105_Jenkins_Hipchat_report.ipynb
  * auto

7. 単体テスト（Unit Test）を走らせてみよう
  * 106_Jenkins_単体テスト実行ジョブ.pdf -> 106_Jenkins_Unit_Test.ipynb
  * 106_Tiny_web_example_unit_test.ipynb
  * auto

6. パッケージ（RPM）を作成してみよう
  * 107_RPM_生成方法.pdf -> 107_RPM_Create.ipynb
  * 107_RPM_Tiny_web_example_create.ipynb
  * auto

7. パッケージ（RPM）を管理するリポジトリを作成してみよう
  * 108_YUM_リポジトリの準備.pdf -> 108_YUM_Repository.ipynb
  * 108_YUM_Tiny_web_example_repository.ipynb
  * auto

## 2日目
8. マシンイメージを作成してみる
  * 204_マシンイメージの作り方.pdf -> 204_Create_Machine_Image.ipynb
  * convert only
  * 5-tiny_web_imagebuild.ipynb -> 204

9. WebAPI / Musscel
  * 203_WebAPI_コマンドマニュアル.pdf -> 203_WebAPI_Command_Reference.ipynb
  * convert only

10. 擬似本番環境を構築する
11. 結合テストの実行をしてみる
12. 擬似本番環境を破棄する
  * 202_パラメタ付きビルド.pdf -> 202_Post_build_trigger.ipynb
  * convert only
  * 6-tiny_web_integration.ipynb -> 202
  * 7-tiny_web_automate.jpynb -> 202

13. 課題０
  a. ソースコードの修正後のCI開始契機を検討し、設定してみよう
    * 201_プルリクエストによるマージ.pdf -> 201_PullRequest_and_Mearge.ipynb
    * <del>105_Jenkins_HipChatへのレポート.pdfの後半にあるリポジトリをポーリングする方法</del>
    * convert only

  b. Hubotのインストール
    * 205_Hubot_インストール.pdf -> 205_Hubot_installation.ipynb
    * 206_Hubot_HipChatへの参加.pdf -> 206_Hubot_Hipchat_relation.ipynb
    * convert only

  C. 一度通しで動作するか確認してみてください

**Comment by triggers** [comment]
This new branch attempts to implement the above file names:
https://github.com/axsh/nii-project-2016/tree/change-to-final-names-attempt1

For commit
https://github.com/axsh/nii-project-2016/commit/6e09d43a44295bb3f81243d408e1455cf03c80b3
these are currently
https://github.com/axsh/nii-project-2016/tree/6e09d43a44295bb3f81243d408e1455cf03c80b3/notebooks

After deleting the temporary prefix, they would look something like this:
```
101_HipChat_setup.TODO.ipynb
102_Jenkins_setup.ipynb
103_jenkins_job_execution_script.ipynb
104_jenkins_github_operation.ipynb
105_HipChat_reports.ipynb
106_unit_test_job_execution.ipynb
106b_Tiny_web_example_unit_test.ipynb
107_how_to_generate_RPM.ipynb
107b_RPM_Tiny_web_example_create.ipynb
108_preparing_yum_repository.ipynb
108b_YUM_Tiny_web_example_repository.ipynb
204_Create_Machine_Image.TODO.ipynb
204b_Tiny_web_example_Create_Machine_Image.ipynb
203_WebAPI_Command_Reference.TODO.ipynb
202_Post_build_trigger.TODO.ipynb
202b-Tiny_web_integration.ipynb
202c-Tiny_web_automate.ipynb
201_PullRequest_and_Mearge.TODO.ipynb
105_Jenkins_HipChat.MAYBE-TODO.ipynb
205_Hubot_installation.TODO.ipynb
206_Hubot_Hipchat_relation.TODO.ipynb
```

**Comment by k-oyakata** [comment]
### Meeting memo 26 Apr. 2016
#### 講義＿演習資料.pdf
* 57ページより前でjupyterの使い方の説明が必要。
* jupyterの資料の番号と講義資料の番号を後で合わせる。

**Comment by k-oyakata** [comment]
#### 102_jenkins_setup
* musselのインストールをどうやるのか、現在はgit clone
* 去年の講義資料ではmusselのインストールはこの時点ではやってない。

** 203_WebAPI_コマンドマニュアル（mussel）にインストールの説明がある。musselの説明時にインストールする **

**Comment by k-oyakata** [comment]
### 103_jenkins_任意のジョブ実行ジョブ
* notebook化するがcheckとかは入れない。

**Comment by k-oyakata** [comment]
#### 104_Jenkins_GitHubポーリング連動
* checkするのはrbenvpluginがインストールされていることだけ
* 3.17と3.18の「シェルの実行」の例(screenshot)がおかしいので直す。

**Comment by k-oyakata** [comment]
#### gg-106b_Tiny_web_example_unit_test
https://github.com/axsh/tiny_web_example/tree/master/webapi/spec
* 学生さんには、上記urlを参考資料にして、実際にjupyterで構築してもらう。
* 各設定は前の資料のリンクを貼ればわかるのではないか。

**Comment by k-oyakata** [comment]
#### 107 and 108 
* 現在のzz-107, zz-108はサンプルを実行するnotebook
* 説明を上記資料に追加する必要がある。

**Comment by k-oyakata** [comment]
#### 201_PullRequest_and_Mearge
* 今回は不要だと思われるが参考資料として残しておくのはいいのではないか。

**Comment by k-oyakata** [comment]
#### 204_Create_Machine_Image
* 今回のイメージビルドはテンプレートを挿入するとイメージビルドができるようになっている。
* どうやってTASKをやらせるのか考える必要がある。
* 去年は参考資料をもとにイメージビルドのジョブを作らせていた。
* どこまでやらせるか？
* 講義資料67,68は参考で使っていたのかmusselのインストールはここでやっていたのか？

**Comment by k-oyakata** [comment]
#### 205 and 206
* 前回の資料からnotebookに移行するだけで良い。

**Comment by k-oyakata** [comment]
### 2日目について
* 学生さんにどんなタスクを実施してもらうか、再検討が必要。
* それぞれ検討して、4/28にまとめる。
* 課題０のタスクも。

**Comment by k-oyakata** [comment]
#### テンプレートをインポートするパターンのシナリオ
1. ユーザにTask入りのテンプレートをコピーしてもらう（Ctrl+Enterで実行）
2. ユーザにTaskを解決してもらう。（Checkはすでにある）
3. **解決できなかった場合に備えて、完全版のテンプレートをコピーする手立てを追加する。**
